# Generated by Django 4.2.16 on 2026-07-19 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='STUDENT', max_length=20)),
                ('member_id', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('join_date', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar_seed', models.CharField(default='Gc', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.CharField(help_text="Custom unique reservation ID, e.g., 'RS-301'", max_length=50, primary_key=True, serialize=False)),
                ('reserve_date', models.DateField(auto_now_add=True)),
                ('queue_position', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Hold'), ('READY', 'Ready for Collection'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed Hold')], default='PENDING', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.CharField(help_text="Custom unique transaction ID, e.g., 'BW-901'", max_length=50, primary_key=True, serialize=False)),
                ('borrow_date', models.DateField()),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Loan'), ('RETURNED', 'Returned/Discharged'), ('OVERDUE', 'Overdue past due date')], default='ACTIVE', max_length=20)),
                ('fine_paid', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
