# Generated by Django 4.2.16 on 2026-07-19 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=50, unique=True)),
                ('published_date', models.DateField()),
                ('copies_total', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('copies_available', models.PositiveIntegerField()),
                ('location', models.CharField(help_text="Physical location coordinates on shelves, e.g. 'Rack A-3, Shelf 2'", max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
            ],
        ),
    ]
